access_key = "<your access_key>"
secret_key = "<your secret_key>"
account_id = "<your aws account id>"
bucket_name = "ecs-access-logs"
app_name = "nodebb_dev"
domain = ""
env_suffix = "dev"
tpl_path = "../network/service.config.json.tpl"